### ISSUE TITLE
Service name is not inherited properly in child spans from parent spans

### ISSUE THREAD

**Issue by kanwals** [DataDog/opencensus-go-exporter-datadog#42] opened 2019-06-25 00:40 UTC
## Summary
The top level span in a trace preserves a configured service name whereas all other spans of the same trace get a default "opencensus-app" service name unless specifically configured each time.

## Description
_Scenario:_ After creating a new `ochttp.Handler` (https://godoc.org/go.opencensus.io/plugin/ochttp#Handler), I pass in a `FormatSpanName` function that gives the top level span a name as the first thing in my API call stack.
As the next step in the call stack, I add a service name by doing:
```
var span = octrace.FromContext(r.Context())
span.AddAttributes(octrace.StringAttribute(ddtraceext.ServiceName, "service-name"))
```

The service name is correctly associated with top level span name, as expected. All of the rest of the spans have their own span names as configured, but the service names of these child spans somehow defaults to "opencensus-app" rather than inheriting the service name from the parent span.

Please let me know if the issue is unclear.

**Comment by gbbr** [comment] 2019-06-25 06:30
@kanwals I transferred this issue to the correct repository. Would you be so kind as to provide a short snippet of code which clearly helps reproduce the problem? It would help greatly in giving you a quick solution.

**Comment by kanwals** [comment] 2019-06-25 21:40
Thanks for pointing that out @cgilmour and thanks for transferring it over @gbbr .

Here's a snippet that can help reproduce the problem. Assume that the middleware chain of an API consists of:
```
func RegisterAPI(r *mux.Router, c APIContext) {
	r.Handle("/api1/serve",
		alice.New(
			RegisterTracePlugin("LiveRamp.api1"),
			ApplyTraceAttributes("api1-service-name"),
			MiddlewareFoo,
		).ThenFunc(renderResponse),
	).Methods("GET")
}
```

And here are the middleware definitions: 
```
// RegisterTracePlugin instruments the HTTP route with the OpenCensus library's
// trace HTTP plugin
func RegisterTracePlugin(route string) alice.Constructor {
	return func(next http.Handler) http.Handler {
		return &ochttp.Handler{
			Handler:     next,
			Propagation: &b3.HTTPFormat{},
			IsPublicEndpoint: true,
			FormatSpanName: func(req *http.Request) string {
				// For the Datadog exporter, |ochttp.Handler.FormatSpanName|
				// formats what Datadog interprets as the Top-Level Span Name.
				//
				// This parent span name must be static, so we set it to the |route|.
				//
				// https://docs.datadoghq.com/tracing/faq/resource-trace-doesn-t-show-up-under-correct-service/
				// https://help.datadoghq.com/hc/en-us/articles/115000702546-What-is-the-Difference-Between-Type-Service-Resource-and-Name-
				return route
			},
		}

	}
}
```
```
func ApplyTraceAttributes(service string) alice.Constructor {
	var handler = func(w http.ResponseWriter, r *http.Request, next http.Handler) {
		var span = octrace.FromContext(r.Context())

		if span.IsRecordingEvents() {
			var routeName = "unknown"
			var routePath = "unknown"
			var currentRoute = mux.CurrentRoute(r)
			var currentRouteName = currentRoute.GetName()
			if len(currentRouteName) > 0 {
				routeName = currentRouteName
			}
			var currentRoutePath, err = currentRoute.GetPathTemplate()
			if err == nil {
				routePath = currentRoutePath
			}

			span.AddAttributes(
				// NOTE: the Datadog Trace Span Type is |web|.
				// This enables the service to be viewed in
				// Datadog Trace Search & Analytics.
				octrace.StringAttribute(ddtraceext.SpanType, ddtraceext.SpanTypeWeb),

				// Span attributes from request object

				// NOTE: The Datadog Trace Resource name is
				// set to the HTTP operation name, which is a recommended
				// value for HTTP traces.
				
				octrace.StringAttribute(ddtraceext.ServiceName, service),
				octrace.StringAttribute(ddtraceext.ResourceName, r.Method),

				octrace.StringAttribute(ochttp.HostAttribute, r.Host),
				octrace.StringAttribute("http.route", routeName),
				octrace.StringAttribute("http.route_path", routePath),
			)
		}

		next.ServeHTTP(w, r)
	}
	return alice.ConstructorFunc(handler)
}
```
```
func MiddlewareFoo(next http.Handler) http.Handler {
	var handler = func(w http.ResponseWriter, r *http.Request) {
		var _, span = octrace.StartSpan(r.Context(), "childspan")
		defer span.End()
		// loads of logic
		// .
		// .
		// .
		next.ServeHTTP(w, r)
	}
	return http.HandlerFunc(handler)
}
```

Now the `childspan` somehow gets the service name as "opencensus-app" instead of inheriting the service-name "api1-service-name" from the parent span.

Hope this provides more clarity.

**Comment by coignetp** [comment] 2021-05-12 11:32
Hi @kanwals, sorry for the delay of this answer and thank you for the code you provided.

Unfortunately, after investigation it seems like we can’t support this use case. We can’t really get parent span attributes, so we can't inherit a service name through a `service.name` attribute. Moreover, it does not really fit the general idea of the datadog opencensus exporter, to have multiple service names for a single exporter. 

You can still set the global service name with the datadog option `datadog.Options{Service: "my-app"}` for an exporter, so all the children span will have the same service name.

I'm closing this issue since we won't implement something around it, but please let me know if the global option I suggested is enough.

**Closed by coignetp** 2021-05-12 11:32 UTC
Labels: trace
